apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-order-gateway
  name: order-gateway3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-order-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-order-gateway
    spec:
      containers:
        - name: order-gateway3
          image: srourzaher/order-gateway3:latest
          ports:
            - containerPort: 8085

