apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-order-eureka
  name: order-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-order-eureka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-order-eureka
    spec:
      containers:
        - name: order-eureka
          image: srourzaher/order-eureka
          ports:
            - containerPort: 8761

